name: OWASP ZAP Integration with GitHub Actions

# This workflow runs whenever there is a push to the repository
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest  
    name: Scan the webapplication  
    steps: 
        # Checks out the repository code so that ZAP can access necessary files
      - name: Checkout 
        uses: actions/checkout@v4  
        with:
          ref: main 

        # Runs the OWASP ZAP full scan action
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0  
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  # Specifies the stable OWASP ZAP Docker image
          target: 'http://testphp.vulnweb.com/'  # Defines the web application URL to scan for vulnerabilities
          cmd_options: '-a'  # Enables aggressive mode to perform a more thorough security scan
