name: owasp zap integration with github actions

# This workflow runs whenever there is a push to the repository
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu virtual machine
    name: Scan the webapplication  # Naming the job for better readability

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Checks out the repository code so that ZAP can access necessary files
        with:
          ref: main  # Ensures that the latest code from the main branch is used

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0  # Runs the OWASP ZAP full scan action
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  # Specifies the stable OWASP ZAP Docker image
          target: 'http://testphp.vulnweb.com/'  # Defines the web application URL to scan for vulnerabilities
          cmd_options: '-a'  # Enables aggressive mode to perform a more thorough security scan
